/**
 * Volunteerist configuration — the single place to change behavior.
 * Headers are matched by text, so renaming a tab/column requires editing
 * here (and re-running Set Up to re-add anything missing).
 */
export const CONFIG = {
  tabNames: {
    directory: 'Directory',
    menu: 'Menu of Asks',
    tracker: 'Tracker',
    settings: 'Settings',
    /** Clean name given to the linked form's response tab. */
    responses: 'Sign-ups',
    /** Where raw responses go when intake is regenerated. */
    archive: 'Sign-ups archive',
  },
  /** Form questions the tracker depends on. Setup validates these exist. */
  requiredFields: {
    name: 'Name',
    email: 'Email',
    phone: 'Phone',
  },
  /**
   * Optional Form answers the Directory mirrors. `title` names both the Form
   * question and the Directory header — the script matches columns by text,
   * so one name keeps the two in sync.
   */
  optionalFields: {
    about: {
      title: 'About',
      /** Description shown under the generated form's About question. */
      helpText:
        'Share anything about yourself, your life, or your reason for volunteering that you want us to know :)',
    },
  },
  /** The Form's first column, present on every submission. */
  timestampField: 'Timestamp',
  /** Title given to an intake form generated by Set Up. */
  intakeFormTitle: 'Volunteer Sign-ups',
  /** Script-managed intake columns the coordinator edits on the Directory. */
  directoryColumns: {
    reachOutBy: 'Reach out by',
    firstContactEvent: 'Calendar Event ID',
  },
  /** Column headers on the Tracker tab, in order. */
  trackerColumns: {
    name: 'Name',
    email: 'Email',
    ask: 'Ask',
    deadline: 'Deadline',
    preTouch: 'Pre-touch',
    postTouch: 'Post-touch',
    preTouchEvent: 'Pre-touch Event ID',
    postTouchEvent: 'Post-touch Event ID',
    notes: 'Notes',
    done: 'Done',
  },
  /** Two-column label/value layout for the Settings tab. */
  settingsColumns: {
    label: 'Setting',
    value: 'Value',
  },
  /** Timing knobs: seeded into the Settings tab, read at use time. */
  settings: {
    firstContactDays: { label: 'First contact (days after signup)', default: 1 },
    preDaysBefore: { label: 'Pre-touch (days before deadline)', default: 2 },
    postDaysAfter: { label: 'Post-touch (days after deadline)', default: 3 },
    reminderHour: { label: 'Reminder hour (24h)', default: 9 },
  },
  /** The one Calendar a Campaign's Touchpoints live on. */
  calendar: {
    /** Settings row recording the calendar id, so every editor resolves it. */
    settingLabel: 'Campaign calendar',
    /** Created-calendar name; suffixed with the spreadsheet's name. */
    namePrefix: 'Volunteer reminders',
    description:
      'Touchpoint reminders for this campaign, created by Volunteer Tools → Set Up. Share it with the campaign team to give them the same reminders.',
  },
  touch: {
    /** Event length in minutes. */
    durationMinutes: 30,
  },
  /**
   * Presentation of the script-generated tabs: columns are fit to their
   * content, text wraps, and the header and machine columns are styled so a
   * coordinator can scan the sheet.
   */
  sheetFormat: {
    /** Columns wider than this wrap instead of stretching the tab. */
    maxColumnWidth: 300,
    /** Rows pre-formatted so rows written later inherit wrapping. */
    wrapRows: 1000,
    headerBackground: '#f1f3f4',
    headerFontColor: '#202124',
    /** Machine bookkeeping (event ids) recedes behind the coordinator's columns. */
    mutedFontColor: '#80868b',
    mutedFontSize: 9,
  },
  /** Starter list seeded into a freshly created Menu of Asks. */
  defaultAsks: [
    'Canvassing (base)',
    'Canvassing (persuasion)',
    'Phone banking',
    'Data entry',
    'Event setup',
  ],
} as const;

export type TouchKind = 'first-contact' | 'pre' | 'post';
